/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/Alert.vue')['default']
    AnimateBar: typeof import('./src/components/AnimateBar.vue')['default']
    Background: typeof import('./src/components/ui/Background.vue')['default']
    CesiumMap: typeof import('./src/components/CesiumMap.vue')['default']
    Code: typeof import('./src/components/layout/Code.vue')['default']
    ColorPicker: typeof import('./src/components/ui/ColorPicker.vue')['default']
    ConfettiCanvas: typeof import('./src/components/ui/ConfettiCanvas.vue')['default']
    copy: typeof import('./src/components/layout/Code copy.vue')['default']
    CSidebar: typeof import('./src/components/ui/CSidebar.vue')['default']
    Demo: typeof import('./src/components/layout/Demo.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    GeneratorBySVG: typeof import('./src/components/GeneratorBySVG.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HighlightCode: typeof import('./src/components/ui/HighlightCode.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    Options: typeof import('./src/components/layout/Options.vue')['default']
    Preview: typeof import('./src/components/layout/Preview.vue')['default']
    RangeBar: typeof import('./src/components/ui/RangeBar.vue')['default']
    Render: typeof import('./src/components/layout/Render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGCode: typeof import('./src/components/layout/SVGCode.vue')['default']
    TextareaCode: typeof import('./src/components/ui/TextareaCode.vue')['default']
    Toolbar: typeof import('./src/components/ui/Toolbar.vue')['default']
    Tools: typeof import('./src/components/layout/Tools.vue')['default']
  }
}
