/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimateBar: typeof import('./src/components/AnimateBar.vue')['default']
    Background: typeof import('./src/components/ui/Background.vue')['default']
    CesiumMap: typeof import('./src/components/CesiumMap.vue')['default']
    CSidebar: typeof import('./src/components/ui/CSidebar.vue')['default']
    GeneratorBySVG: typeof import('./src/components/GeneratorBySVG.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Options: typeof import('./src/components/layout/Options.vue')['default']
    Preview: typeof import('./src/components/layout/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/ui/Toolbar.vue')['default']
  }
}
